wahanegi/vibereport

Gemfile.lock
README.md

[![CI-12](https://badgen.net/badge/JIRA/CI-12/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-12)
[CI-12]: https://cloverpop-internship.atlassian.net/browse/CI-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-12: Create a README

---

README.md

[![CI-13](https://badgen.net/badge/JIRA/CI-13/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-13)
[CI-13]: https://cloverpop-internship.atlassian.net/browse/CI-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-13: Added MIT License to README

---

.codeclimate.yml
.rubocop.yml
Gemfile
Gemfile.lock
README.md

[![CI-16](https://badgen.net/badge/JIRA/CI-16/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-16)

CI-16: Add CodeClimate integration

---

Gemfile
Gemfile.lock
app/controllers/home_controller.rb
app/javascript/components/App.js
app/javascript/controllers/index.js
app/javascript/controllers/react_controller.js
app/views/home/app.html.erb
app/views/home/index.html.erb
config/routes.rb
package.json
spec/requests/react_spec.rb
yarn.lock

[![CI-53](https://badgen.net/badge/JIRA/CI-53/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-53)
Added gem 'jsonapi-serializer' to Gemfile
[CI-53]: https://cloverpop-internship.atlassian.net/browse/CI-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-53: React Gateway

---

README.md

[![CI-58](https://badgen.net/badge/JIRA/CI-58/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-58)
Start Rails server
[CI-58]: https://cloverpop-internship.atlassian.net/browse/CI-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-58: add to Start Rails server

---

app/admin/users.rb
spec/requests/admin/users_spec.rb

[![CI-73](https://badgen.net/badge/JIRA/CI-73/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-73)
[CI-73]: https://cloverpop-internship.atlassian.net/browse/CI-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-73: User cant be updated from Active Admin

---

app/views/passwordless/sessions/new.html.erb

[![CI-96](https://badgen.net/badge/JIRA/CI-96/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-96)
[CI-96]: https://cloverpop-internship.atlassian.net/browse/CI-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-96: Unnecessary Dashboard Log-in link is present on Access Site page

---

app/assets/stylesheets/main.scss

[![CI-106](https://badgen.net/badge/JIRA/CI-106/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-106)
[CI-106]: https://cloverpop-internship.atlassian.net/browse/CI-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-106: The "Email" field has wrong width on Access Site page

---

app/views/passwordless/sessions/create.html.erb

[![CI-105](https://badgen.net/badge/JIRA/CI-105/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-105)
[CI-105]: https://cloverpop-internship.atlassian.net/browse/CI-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-105: Line breaks are absent for the “If you have any issues..”

---

Gemfile
Gemfile.lock
config/environments/production.rb
test/test_helper.rb

[![CI-9](https://badgen.net/badge/JIRA/CI-9/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-9)

CI-9: Configure Postmarkapp to work with production

---

app/assets/stylesheets/design_system_vibereport.scss
app/javascript/components/Pages/EmotionIntensity.js

[![CI-170](https://badgen.net/badge/JIRA/CI-170/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-170)
https://cloverpop-internship.atlassian.net/browse/CI-172 -The "Select how intense the feeling was!" text color doesn't match specs on Emotion Intensity page
https://cloverpop-internship.atlassian.net/browse/CI-173 - The ""same emotion" week? Most excellent! Select how intense the feeling was" text color doesn't match specs on Emotion Intensity page.
[CI-170]: https://cloverpop-internship.atlassian.net/browse/CI-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-170: The "Excellent choice!" text color doesn't match specs on Selected Giphy Follow page

---

app/javascript/components/Pages/ProductivityBadFollowUp.js

[![CI-219](https://badgen.net/badge/JIRA/CI-219/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-219)
[CI-219]: https://cloverpop-internship.atlassian.net/browse/CI-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-219: Users are not redirected on Celebrate page from the Productivity Follow-up page.

---

app/javascript/components/UI/mention/mentionsInputStyles.js

[![CI-216](https://badgen.net/badge/JIRA/CI-216/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-216)
[CI-216]: https://cloverpop-internship.atlassian.net/browse/CI-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-216: Dropdown list run over text after entering the "@" symbol into the field on Celebrate page

---

app/javascript/components/Pages/EmotionEntry.js

[![CI-205](https://badgen.net/badge/JIRA/CI-205/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-205)
[CI-205]: https://cloverpop-internship.atlassian.net/browse/CI-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-205: Update text on the Emotion Entry page

---

app/javascript/components/Pages/ProductivityCheckLow.js
app/javascript/components/__tests__/ProductivityCheckLow.test.js

[![CI-209](https://badgen.net/badge/JIRA/CI-209/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-209)
[CI-209]: https://cloverpop-internship.atlassian.net/browse/CI-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-209: Update text on the Productivity Check page

---

app/javascript/components/Pages/EmotionIntensity.js

[![CI-206](https://badgen.net/badge/JIRA/CI-206/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-206)
[CI-206]: https://cloverpop-internship.atlassian.net/browse/CI-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-206: Update text on the Emotion Intensity page

---

app/javascript/components/Pages/ListEmotions.js
app/javascript/components/__tests__/ListEmotions.test.js

[![CI-203](https://badgen.net/badge/JIRA/CI-203/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-203)
[CI-203]: https://cloverpop-internship.atlassian.net/browse/CI-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-203: Update text on the Emotion Selection Web page

---

app/views/passwordless/sessions/create.html.erb

[![CI-196](https://badgen.net/badge/JIRA/CI-196/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-196)
[CI-196]: https://cloverpop-internship.atlassian.net/browse/CI-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-196:  Text replacing "an" with "a" on Sign in page

---

app/assets/stylesheets/design_system_vibereport.scss
app/javascript/components/Pages/ListEmotions.js

[![CI-198](https://badgen.net/badge/JIRA/CI-198/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-198)
[CI-198]: https://cloverpop-internship.atlassian.net/browse/CI-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-198: The burger menu icon is not scrolled down and up on Emotion Selection Web page

---

app/assets/stylesheets/main.scss
app/views/passwordless/sessions/new.html.erb

[![CI-237](https://badgen.net/badge/JIRA/CI-237/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-237)
[CI-237]: https://cloverpop-internship.atlassian.net/browse/CI-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-237: Space is absent in the "Enter Email here" field after entering the email address on Sign in page

---

app/assets/stylesheets/design_system_vibereport.scss
app/assets/stylesheets/icebreaker_answer.scss
app/javascript/components/Pages/IcebreakerAnswer.js

[![CI-272](https://badgen.net/badge/JIRA/CI-272/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-272)
[CI-272]: https://cloverpop-internship.atlassian.net/browse/CI-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-272: Update scrollbar acc to updated requirements on Icebreaker page.

---

app/assets/stylesheets/main.scss
app/javascript/components/Pages/EmotionIntensity.js
app/javascript/components/Pages/ProductivityBadFollowUp.js

[![CI-276](https://badgen.net/badge/JIRA/CI-276/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-276)
And CI-274: Update scrollbar acc to updated requirements on Emotion Intensity page
[CI-276]: https://cloverpop-internship.atlassian.net/browse/CI-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-276: Update scrollbar acc to updated requirements on the Productivity Follow-up page.

---

app/assets/stylesheets/main.scss
app/views/passwordless/sessions/create.html.erb
app/views/passwordless/sessions/new.html.erb

[![CI-361](https://badgen.net/badge/JIRA/CI-361/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-361)
[CI-361]: https://cloverpop-internship.atlassian.net/browse/CI-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-361:The location of the "Next" button does not meet the specs

---

app/admin/shoutouts.rb

[![CI-380](https://badgen.net/badge/JIRA/CI-380/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-380)
[CI-380]: https://cloverpop-internship.atlassian.net/browse/CI-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-380: Add the ability to delete Shoutouts in Shoutouts tab in Active Admin

---

app/assets/stylesheets/icebreaker_answer.scss
app/javascript/components/Pages/IcebreakerAnswer.js
app/javascript/components/Pages/IcebreakerQuestion.js

[![CI-385](https://badgen.net/badge/JIRA/CI-385/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-385)
[CI-385]: https://cloverpop-internship.atlassian.net/browse/CI-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-385: The text box frame design on Submit Icebreaker and Icebreaker pages does not meet the specs.

---

app/javascript/components/UI/rich-text/RichInputElement.js
app/javascript/components/UI/rich-text/cursor.js

[![CI-388](https://badgen.net/badge/JIRA/CI-388/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-388)
[CI-388]: https://cloverpop-internship.atlassian.net/browse/CI-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-388: The scroll jumps to a higher position on all pages when entering the "@" symbol

---

app/assets/stylesheets/icebreaker_answer.scss

[![CI-384](https://badgen.net/badge/JIRA/CI-384/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-384)
[CI-384]: https://cloverpop-internship.atlassian.net/browse/CI-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-384: The mouse cursor is not changed to the text cursor 

---

app/assets/stylesheets/main.scss
app/javascript/components/Pages/IcebreakerAnswer.js
app/javascript/components/Pages/IcebreakerQuestion.js
app/javascript/components/UI/BlockLowerBtns.js

[![CI-324](https://badgen.net/badge/JIRA/CI-324/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-324)
[CI-324]: https://cloverpop-internship.atlassian.net/browse/CI-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-324/CI-325: Fix for  'Back' and 'Skip to Results' buttons location on the Submit Icebreaker page

---

app/javascript/components/Pages/ResultsPage/EmotionSection.js
app/javascript/components/Pages/ResultsPage/ResultsPreview.js
app/javascript/components/Pages/ResultsPage/index.js
app/javascript/components/UI/CornerElements.js
app/javascript/components/UI/Menu.js
app/presenters/api/v1/results_presenter.rb
config/routes.rb
spec/presenters/results_presenter_spec.rb

[![CI-452](https://badgen.net/badge/JIRA/CI-452/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-452)
[CI-452]: https://cloverpop-internship.atlassian.net/browse/CI-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-452: The user is redirected to a blank page after clicking the "See the Results" button on the Results email.

---

app/helpers/user_email_mailer_helper.rb
app/javascript/components/Pages/ResultsPage/EmotionSection.js
app/workers/results_notification_worker.rb

[![CI-340](https://badgen.net/badge/JIRA/CI-340/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-340)
[CI-340]: https://cloverpop-internship.atlassian.net/browse/CI-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-340: Update Results/Results Email pages.

---

app/javascript/components/helpers/helpers.js

[![CI-465](https://badgen.net/badge/JIRA/CI-465/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-465)
[CI-465]: https://cloverpop-internship.atlassian.net/browse/CI-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-465: The Skip button is absent on Meme selection page

---

app/assets/stylesheets/main.scss

[![CI-391](https://badgen.net/badge/JIRA/CI-391/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-391)
[CI-391]: https://cloverpop-internship.atlassian.net/browse/CI-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-391: [Mozila] The slider bar design doesn't meet specs on Productivity Check page

---

app/mailers/user_email_mailer.rb

[![CI-464](https://badgen.net/badge/JIRA/CI-464/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-464)
[CI-464]: https://cloverpop-internship.atlassian.net/browse/CI-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-464: Nonpublic emotions are displayed on the Emotion Selection Email

---

app/assets/stylesheets/main.scss

[![CI-463](https://badgen.net/badge/JIRA/CI-463/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-463)
[CI-463]: https://cloverpop-internship.atlassian.net/browse/CI-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-463: The pointer cursor is shown when hovering on the disabled Save draft button in the Drop-down

---

app/javascript/components/UI/CornerElements.js
app/javascript/components/UI/ShoutoutButton.js

[![CI-473](https://badgen.net/badge/JIRA/CI-473/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-473)
[CI-473]: https://cloverpop-internship.atlassian.net/browse/CI-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-473: The large/small "Shoutout" button is not present on the Recognition page

---

app/assets/stylesheets/email_page.css
app/views/user_email_mailer/response_invite.html.erb
config/environments/development.rb

[![CI-477](https://badgen.net/badge/JIRA/CI-477/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-477)
https://cloverpop-internship.atlassian.net/browse/CI-477
[CI-477]: https://cloverpop-internship.atlassian.net/browse/CI-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-477:The location of the 'I was not working recently' link doesn't meet the specs on the Emotion Selection email

---

app/javascript/components/Pages/Recognition.js
app/javascript/components/UI/Menu.js
app/javascript/components/UI/modal/Portal.js

[![CI-459](https://badgen.net/badge/JIRA/CI-459/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-459)
[CI-459]: https://cloverpop-internship.atlassian.net/browse/CI-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-459: Change the behavior of the Drop down menu on the "Rather not say" and the "Skip ahead" pages

---

app/reports/emotion_index.rb

[![CI-349](https://badgen.net/badge/JIRA/CI-349/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-349)
[CI-349]: https://cloverpop-internship.atlassian.net/browse/CI-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-349: Update Reports.

---

app/javascript/components/Pages/ListEmotions.js

[![CI-481](https://badgen.net/badge/JIRA/CI-481/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-481)
[CI-481]: https://cloverpop-internship.atlassian.net/browse/CI-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-481: The productivity "0" is displayed in Responses tab of Active Admin before inputting productivity level

---

app/javascript/components/UI/Menu.js

[![CI-480](https://badgen.net/badge/JIRA/CI-480/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-480)
[CI-480]: https://cloverpop-internship.atlassian.net/browse/CI-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-480: Change the behavior of the Drop down menu on the "Unsubscribe" pages

---

app/models/time_period.rb
spec/models/time_period_spec.rb

[![CI-394](https://badgen.net/badge/JIRA/CI-394/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-394)
[CI-394]: https://cloverpop-internship.atlassian.net/browse/CI-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-394: Change start and end dates of the time period.

---

app/assets/stylesheets/main.scss

[![CI-215](https://badgen.net/badge/JIRA/CI-215/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-215)
[CI-215]: https://cloverpop-internship.atlassian.net/browse/CI-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-215: Scroll bar doesn't meet the specs on dropdown list after entering the "@" symbol into the field on Celebrate page

---

app/assets/stylesheets/icebreaker_answer.scss
app/assets/stylesheets/main.scss

[![CI-460](https://badgen.net/badge/JIRA/CI-460/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-460)
[CI-460]: https://cloverpop-internship.atlassian.net/browse/CI-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-460: The text is moved on the Emotion Intensity and Productivity Bad Follow Up Celebrate pages after clicking the text field

---

app/assets/stylesheets/gif.scss

[![CI-275](https://badgen.net/badge/JIRA/CI-275/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-275)
[CI-275]: https://cloverpop-internship.atlassian.net/browse/CI-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-275: Update Meme Selection field acc to updated specs on Meme Selection page.

---

app/admin/dashboard.rb
app/helpers/active_admin_helpers.rb
app/javascript/components/Pages/EmotionIntensity.js
app/javascript/components/Pages/MemeSelection.js
app/javascript/components/__tests__/CausesToCelebrate.test.js
app/javascript/components/__tests__/ListEmotions.test.js
app/javascript/components/helpers/consts.js
app/models/emotion.rb
app/serializers/emotion_serializer.rb
app/workers/results_notification_worker.rb
db/seeds/starting_emotions.yml
spec/factories/emotions.rb
spec/models/emotion_spec.rb
spec/requests/emotions_spec.rb

[![CI-466](https://badgen.net/badge/JIRA/CI-466/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-466)
NOTE: After merging this brunch into master please run in console:
`Emotion.where.not(category: :negative).where.not(category: :positive).destroy_all`
[CI-466]: https://cloverpop-internship.atlassian.net/browse/CI-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-466: Remove Neutral Emotions from code and database

---

app/javascript/components/Pages/ResultsPage/NavigationBar.js
app/javascript/components/UI/ShareContent.js

[![CI-467](https://badgen.net/badge/JIRA/CI-467/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-467)
[CI-467]: https://cloverpop-internship.atlassian.net/browse/CI-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-467: The calendar icon's design doesn't meet the specs on the Results page

---

app/presenters/api/v1/results_presenter.rb

[![CI-435](https://badgen.net/badge/JIRA/CI-435/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-435)
[CI-435]: https://cloverpop-internship.atlassian.net/browse/CI-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-435: The content of Shoutout section doesn't meet specs on Results page on previous time periods.

---

app/controllers/application_controller.rb

[![CI-483](https://badgen.net/badge/JIRA/CI-483/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-483)
[CI-483]: https://cloverpop-internship.atlassian.net/browse/CI-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-483: CORS Issue: Fonts blocked on production server when herokuapp domain used

---

app/javascript/components/Pages/EmotionIntensity.js
app/javascript/components/UI/rich-text/RichInputElement.js
app/javascript/components/UI/rich-text/RichTextArea.js

[![CI-393](https://badgen.net/badge/JIRA/CI-393/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-393)
[CI-393]: https://cloverpop-internship.atlassian.net/browse/CI-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-393: Change the behavior of the placeholder when entering text on the Emotion Intensity and Shoutout text field

---

app/assets/stylesheets/main.scss
app/javascript/components/Pages/MemeSelection.js

[![CI-475](https://badgen.net/badge/JIRA/CI-475/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-475)
[CI-475]: https://cloverpop-internship.atlassian.net/browse/CI-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-475: The location of the 'Back' and 'Next'/'Upload your own meme' and 'Next' buttons don't meet the specs on the Emotion Entry/Meme Selection pages

---

app/assets/stylesheets/main.scss
app/javascript/components/Pages/ResultsPage/ShoutoutAwards.js

[![CI-488](https://badgen.net/badge/JIRA/CI-488/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-488)
[CI-488]: https://cloverpop-internship.atlassian.net/browse/CI-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-488: The "Shoutout" text is located incorrectly in the Most Active Awards section on the Results page

---

app/admin/responses.rb

[![CI-490](https://badgen.net/badge/JIRA/CI-490/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-490)
[CI-490]: https://cloverpop-internship.atlassian.net/browse/CI-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-490: Do not show the user's No public Emotions in Response Details of Active Admin

---

app/admin/celebrate_shoutouts.rb
app/admin/fun_question.rb
app/admin/fun_question_answer.rb
app/admin/notifications.rb
app/admin/responses.rb
app/admin/shoutouts.rb
app/admin/teams.rb
app/admin/time_periods.rb
app/admin/users.rb

[![CI-491](https://badgen.net/badge/JIRA/CI-491/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-491)
[CI-491]: https://cloverpop-internship.atlassian.net/browse/CI-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-491: Change the order of displaying time periods in Active Admin

---

app/assets/stylesheets/main.scss
app/assets/stylesheets/results.scss
app/javascript/components/Pages/MemeSelection.js
app/javascript/components/Pages/ResultsPage/NavigationBar.js

[![CI-462](https://badgen.net/badge/JIRA/CI-462/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-462)
[CI-462]: https://cloverpop-internship.atlassian.net/browse/CI-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-462: Locate all HUD elements acc to specs on all pages

---

app/javascript/components/Pages/ResultsPage/ShoutoutAwards.js
app/javascript/components/Pages/ResultsPage/ShoutoutSection.js

[![CI-487](https://badgen.net/badge/JIRA/CI-487/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-487)
[CI-487]: https://cloverpop-internship.atlassian.net/browse/CI-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-487: Hide text on results page if there are no results

---

app/admin/responses.rb
app/presenters/api/v1/results_presenter.rb

[![CI-493](https://badgen.net/badge/JIRA/CI-493/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-493)
[CI-493]: https://cloverpop-internship.atlassian.net/browse/CI-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-493: Broken Gif icon is shown on the Results page when No Results found on Meme selection page

---

app/assets/stylesheets/email_page.css
app/javascript/components/Pages/ListEmotions.js

[![CI-499](https://badgen.net/badge/JIRA/CI-499/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-499)
[CI-499]: https://cloverpop-internship.atlassian.net/browse/CI-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-499: The calendar icon is absent on Emotion Selection Web

---

app/controllers/api/v1/responses_controller.rb
app/mailers/user_email_mailer.rb
app/services/api/v1/response_flow_from_email.rb
spec/services/api/v1/response_flow_from_email_spec.rb

[![CI-501](https://badgen.net/badge/JIRA/CI-501/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-501)
[CI-501]: https://cloverpop-internship.atlassian.net/browse/CI-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-501: The user is redirected to Emotion Selection Web page after clicking any button in Emotion Selection Email

---

app/models/time_period.rb
app/workers/emotion_selection_notification_worker.rb
config/environments/development.rb
spec/factories/time_periods.rb
spec/models/time_period_spec.rb
spec/workers/emotion_selection_notification_worker_spec.rb

[![CI-500](https://badgen.net/badge/JIRA/CI-500/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-500)
[CI-500]: https://cloverpop-internship.atlassian.net/browse/CI-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-500: Modify conditions for creating Due Dates in Active Admin

---

app/javascript/components/Pages/ListEmotions.js
app/javascript/components/__tests__/ListEmotions.test.js
app/views/user_email_mailer/response_invite.html.erb

[![CI-505](https://badgen.net/badge/JIRA/CI-505/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-505)
[CI-505]: https://cloverpop-internship.atlassian.net/browse/CI-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-505: Change the verbiage on the Emotion Selection Email/Emotion Selection Web

---

app/javascript/components/UI/ToggleEmotionType.js

[![CI-506](https://badgen.net/badge/JIRA/CI-506/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-506)
[CI-506]: https://cloverpop-internship.atlassian.net/browse/CI-506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-506: Change the verbiage on the Emotion Entry/Emotion Type pages

---

app/assets/stylesheets/results.scss
app/javascript/components/Pages/ResultsPage/QuestionSection.js

[![CI-507](https://badgen.net/badge/JIRA/CI-507/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-507)
[CI-507]: https://cloverpop-internship.atlassian.net/browse/CI-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-507: Remove the expansion and contraction feature in the Icebreaker section on the Results page

---

app/assets/stylesheets/buttons.scss
app/assets/stylesheets/gif.scss
app/javascript/components/Pages/ResultsPage/GifSection.js
app/presenters/api/v1/results_presenter.rb
package.json
spec/presenters/results_presenter_spec.rb
yarn.lock

[![CI-508](https://badgen.net/badge/JIRA/CI-508/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-508)
[CI-508]: https://cloverpop-internship.atlassian.net/browse/CI-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-508: Add hover tooltip over selected meme on the Results page

---

app/javascript/components/Pages/ResultsPage/ShoutoutItem.js

[![CI-509](https://badgen.net/badge/JIRA/CI-509/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-509)
[CI-509]: https://cloverpop-internship.atlassian.net/browse/CI-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-509: Remove the expansion and contraction feature in the Shoutouts section on the Results page

---

app/assets/stylesheets/colors.scss
app/assets/stylesheets/main.scss
app/assets/stylesheets/results.scss
app/controllers/api/v1/fun_question_answers_controller.rb
app/javascript/components/Pages/ResultsPage/QuestionSection.js
app/javascript/components/Pages/ResultsPage/index.js
app/presenters/api/v1/results_presenter.rb
spec/presenters/results_presenter_spec.rb
spec/requests/fun_question_answers_spec.rb

[![CI-512](https://badgen.net/badge/JIRA/CI-512/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-512)
[CI-512]: https://cloverpop-internship.atlassian.net/browse/CI-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-512: Add the ability to edit Icebreaker answer on the Results page

---

app/javascript/components/Pages/ResultsPage/QuestionSection.js

[![CI-513](https://badgen.net/badge/JIRA/CI-513/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-513)
[CI-513]: https://cloverpop-internship.atlassian.net/browse/CI-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-513: Icebreaker answers from the current time period are displayed in the previous time period

---

app/javascript/components/Pages/ResultsPage/ResultsPreview.js

[![CI-520](https://badgen.net/badge/JIRA/CI-520/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-520)
[CI-520]: https://cloverpop-internship.atlassian.net/browse/CI-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-520: The user is redirected to a blank page after clicking the "See the Results" button on the Results email.

---

app/admin/dashboard.rb
app/admin/responses.rb
app/assets/stylesheets/active_admin.scss
app/assets/stylesheets/main.scss
app/controllers/api/v1/users_controller.rb
app/helpers/active_admin_helpers.rb
app/helpers/application_helper.rb
app/mailers/user_email_mailer.rb
app/views/user_email_mailer/send_reminder.html.erb
config/routes.rb
spec/requests/users_spec.rb

[![CI-514](https://badgen.net/badge/JIRA/CI-514/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-514)
[CI-514]: https://cloverpop-internship.atlassian.net/browse/CI-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CI-519](https://cloverpop-internship.atlassian.net/browse/CI-519)
[CI-519]: https://cloverpop-internship.atlassian.net/browse/CI-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-514: Create easy way in ActiveAdmin to generate nag emails.

---

app/javascript/components/Pages/ResultsPage/EmotionSection.js

[![CI-526](https://badgen.net/badge/JIRA/CI-526/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-526)
[CI-526]: https://cloverpop-internship.atlassian.net/browse/CI-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-526: Change the color of the emotion words in the word cloud to blue on the Results page

---

app/assets/stylesheets/buttons.scss
app/javascript/components/Pages/CheckInClosed.js

[![CI-533](https://badgen.net/badge/JIRA/CI-533/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-533) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-533]: https://cloverpop-internship.atlassian.net/browse/CI-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-533 Change “Check-in-closed” page content

---

app/javascript/components/Pages/ResultsPage/QuestionSection.js

[![CI-545](https://badgen.net/badge/JIRA/CI-545/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-545) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-545]: https://cloverpop-internship.atlassian.net/browse/CI-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-545: The Icebreaker answers are not displayed on the Results page after clicking "See the Results" button on the Results email

---

app/presenters/api/v1/results_presenter.rb

[![CI-547](https://badgen.net/badge/JIRA/CI-547/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-547) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-547]: https://cloverpop-internship.atlassian.net/browse/CI-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-547: Received and sent Shoutouts aren't displayed for the user if they click "I was not working recently' link on the Results page

---

app/admin/user_teams.rb
app/controllers/api/v1/emotions_controller.rb
app/helpers/user_email_mailer_helper.rb
app/javascript/components/Pages/ResultsPage/NavigationBar.js
app/javascript/components/Pages/UnsubscribePage.js
app/javascript/components/UI/ShareContent.js
app/models/user_team.rb
app/presenters/api/v1/results_presenter.rb
db/migrate/20231017172519_add_role_to_user_team.rb
db/migrate/20231017172808_update_existed_user_team_role.rb
db/migrate/20231017173020_remove_user_team_manager.rb
db/schema.rb
spec/factories/user_teams.rb
spec/models/user_team_spec.rb
spec/presenters/results_presenter_spec.rb

[![CI-546](https://badgen.net/badge/JIRA/CI-546/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-546) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-546]: https://cloverpop-internship.atlassian.net/browse/CI-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-546: Create team observer

---

Gemfile
Gemfile.lock
app/presenters/api/v1/results_presenter.rb
config/environments/development.rb

[![CI-550](https://badgen.net/badge/JIRA/CI-550/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-550) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-550]: https://cloverpop-internship.atlassian.net/browse/CI-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-550: Find, Fix, and Prevent, N+1 Queries on app.

---

app/helpers/user_email_mailer_helper.rb
spec/helpers/user_email_mailer_helper_spec.rb

[![CI-553](https://badgen.net/badge/JIRA/CI-553/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-553) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-553]: https://cloverpop-internship.atlassian.net/browse/CI-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-553: Only describe a team if there is one or more manager assigned to it

---

app/models/response.rb
app/presenters/api/v1/results_presenter.rb
spec/models/response_spec.rb

[![CI-552](https://badgen.net/badge/JIRA/CI-552/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-552) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-552]: https://cloverpop-internship.atlassian.net/browse/CI-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-552: Avoid repeats of the same word + meme in a results dashboard

---

app/admin/dashboard.rb

[![CI-554](https://badgen.net/badge/JIRA/CI-554/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-554) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-554]: https://cloverpop-internship.atlassian.net/browse/CI-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-554: Change the copy/paste reminder message on Dashboard

---

app/admin/fun_question.rb
app/admin/fun_question_answer.rb
spec/admin/fun_question_answers_spec.rb
spec/admin/teams_spec.rb

[![CI-555](https://badgen.net/badge/JIRA/CI-555/0052CC)](https://cloverpop-internship.atlassian.net/browse/CI-555) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
[CI-555]: https://cloverpop-internship.atlassian.net/browse/CI-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CI-555: Add a fun question answers section to ActiveAdmin

---

.github/pr-badge.yml

[![VIB-20](https://badgen.net/badge/JIRA/VIB-20/0052CC)](https://cloverpop-internship.atlassian.net/browse/VIB-20) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)

VIB-20: Fix the JIRA tag settings in Vibereport

---

Gemfile.lock
app/assets/stylesheets/buttons.scss
app/assets/stylesheets/colors.scss
app/assets/stylesheets/design_system_vibereport.scss
app/assets/stylesheets/emition_entry.scss
app/assets/stylesheets/main.scss
app/assets/stylesheets/mixins.scss
app/javascript/components/Pages/EmotionEntry.js

[![VIB-5](https://badgen.net/badge/JIRA/VIB-5/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-5) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Hello Team, please review the PR
_We decided to divide this task into smaller sub-tasks. This PR fix colors.scss file. After all sub-tasks are completed and merged to the VIB-5 branch, we can create the main PR to merge all changes to the master._ 
- Removed unused variables
- Replaced redundant color variables
Please, find attached detail table with all changes made

VIB-5: Check of existence the variables from 'View and style' doc in VibeReport app (COLOR section)

---

app/assets/stylesheets/application.bootstrap.scss
app/assets/stylesheets/typography.scss

[![VIB-5](https://badgen.net/badge/JIRA/VIB-5/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-5) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Hello Team, please review PR
1: Create typography.scss
2. Customized typography variables
3. Enabled RFS (Responsive Font Sizes)
4. Defined a font-size scale
5. Customized body styles
6. Styled headings dynamically
7. Extended Bootstrap utilities

VIB-5 Check of existence the variables from 'View and style' doc in VibeReport app (Typography)

---

Gemfile.lock
app/assets/stylesheets/buttons.scss
app/assets/stylesheets/colors.scss
app/javascript/components/Pages/RatherNotSay/RatherNotSay.js
app/javascript/components/Pages/RatherNotSay/SkipAhead.js
app/javascript/components/Pages/UnsubscribePage.js
app/javascript/components/Pages/modals/NotWorkingModal.js
app/javascript/components/Pages/modals/WorkingModal.js
app/javascript/components/UI/ShareContent.js
app/javascript/components/UI/SweetAlert.js
app/javascript/components/UI/modal/MessageYesNoOk.js
app/javascript/components/UI/rich-text/RichInputElement.js

[![VIB-5](https://badgen.net/badge/JIRA/VIB-5/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-5) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
**Description: Update Buttons and Style Enhancements**
This pull request introduces the following changes to improve button styles and align them with the updated design specifications:
**Summary of Changes:**
**Button Styles:**
- Replaced custom color classes with utility classes for consistency and maintainability.
- Removed unused button classes, including .btn-danger, .back, .padding10-20, and .shadow.
- Updated …

VIB-5-buttons

---

app/assets/stylesheets/design_system_vibereport.scss
app/assets/stylesheets/main.scss
app/javascript/components/Footer.js
app/javascript/components/Pages/CausesToCelebrate.js
app/javascript/components/UI/BlockLowerBtns.js

[![VIB-12](https://badgen.net/badge/JIRA/VIB-12/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-12) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Removed unnecessary custom CSS classes
- Replaced custom CSS properties with bootstrap classes  
- Removed unnecessary html tags
- Changed buttons for a more comfortable layout on mobile devices.

VIB-12: Refactor Causes to Celebrate for mobile-friendly layout

---

app/assets/stylesheets/colors.scss
app/assets/stylesheets/icebreaker_answer.scss
app/assets/stylesheets/typography.scss
app/javascript/components/Pages/IcebreakerAnswer.js
app/javascript/components/UI/BlockLowerBtns.js

[![VIB-14](https://badgen.net/badge/JIRA/VIB-14/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-14) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Hello Team, please review the PR:
- Refactor the layout and styling of the Icebreaker Answer to use the Layout wrapper, which includes the Header and Footer. 
- Most hardcoded CSS classes were replaced with reusable Bootstrap classes
- Refactor styles to be mobile-friendly
Please, review the attached screenshots:
- laptop
- mobile

VIB-14: Refactor Icebreaker Answer for mobile-friendly layout

---

app/javascript/components/Header.js
app/javascript/components/Layout.js
app/javascript/components/Pages/UnsubscribePage.js

[![VIB-22](https://badgen.net/badge/JIRA/VIB-22/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-22) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Fixed error that prevents rendering the Unsubscribe page
- Add responsive font sizes for different displays
- Make sure page is mobile-friendly
Screenshot examples:

VIB-22: Refactor Unsubscribe for mobile-friendly layout

---

app/assets/stylesheets/main.scss
app/javascript/components/Layout.js
app/javascript/components/Pages/EmotionIntensity.js

[![VIB-10](https://badgen.net/badge/JIRA/VIB-10/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-10) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
1) Add Bootstrap grid system (container, row, col-*).
2) Replace inline styles and hardcoded CSS with Bootstrap utility classes where applicable.
3) Created custom classes for specific styles in app/assets/stylesheets/main.scss (.emotion-intensity) 
4) Validate mobile responsiveness.

VIB-10: Refactor Emotion Intensity for mobile-friendly layout

---

app/assets/stylesheets/buttons.scss
app/assets/stylesheets/design_system_vibereport.scss
app/assets/stylesheets/gif.scss
app/assets/stylesheets/main.scss
app/assets/stylesheets/variables.scss
app/javascript/components/Footer.js
app/javascript/components/Layout.js
app/javascript/components/Pages/EmotionType.js
app/javascript/components/Pages/MemeSelection.js
app/javascript/components/Pages/Recognition.js
app/javascript/components/UI/ShareContent.js
app/javascript/components/UI/SwitcherShoutouts.js
app/javascript/components/UI/rich-text/RichInputElement.js
app/javascript/components/UI/rich-text/RichTextArea.js

[![VIB-13](https://badgen.net/badge/JIRA/VIB-13/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-13) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Refactor Update Recognition for mobile-friendly layout
- Add changes to the styles to make mobile-view layout for Recognition page;
- Made clean up in css files, changed to the bootstrap styles;
- Adjust styles for modal window. This adjust is not fully done, because we have different task for modal windows.
-Use url: http://localhost:3000/recognition to get into Recognition page
-Click on ShoutOut img and you will see a …

VIB-13: Refactor Update Recognition for mobile-friendly layout

---

app/assets/stylesheets/email_page.css
app/assets/stylesheets/main.scss
app/assets/stylesheets/results.scss
app/javascript/components/Pages/ResultsPage/EmotionSection.js
app/javascript/components/Pages/ResultsPage/GifSection.js
app/javascript/components/Pages/ResultsPage/NavigationBar.js
app/javascript/components/Pages/ResultsPage/QuestionSection.js
app/javascript/components/Pages/ResultsPage/ShoutoutSection.js
app/javascript/components/Pages/ResultsPage/index.js
app/javascript/components/UI/Loader.js
app/javascript/components/UI/ShareContent.js

[![VIB-16](https://badgen.net/badge/JIRA/VIB-16/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-16) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Removed CSS style lines from components.
- Moved alert content into the `NoticeAlert` component and refactored it
- Moved top content into the `TextHeader` component and refactored it
- Refactored the `NavigationBar` component for mobile-friendly layout and removed unused css classes
- Optimized the animation of words and refactored in the `EmotionSection` component for mobile-friendly layout
- Refactored the …

VIB-16: Refactor Results for mobile-friendly layout

---

app/assets/stylesheets/buttons.scss
app/assets/stylesheets/design_system_vibereport.scss
app/assets/stylesheets/gif.scss
app/javascript/components/Pages/Gifs/GifList.js
app/javascript/components/Pages/Gifs/SearchBar.js
app/javascript/components/Pages/Gifs/index.js
app/javascript/components/Pages/MemeSelection.js
app/javascript/components/UI/ShareContent.js

[![VIB-9](https://badgen.net/badge/JIRA/VIB-9/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-9) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Refactor Meme Selection for mobile-friendly layout
- Add changes to the styles to make mobile-view layout;
- Made clean up in css files, changed to the bootstrap styles;
- Changed layout of the GIFs inside the GIF-list to make the GIFs visible on the mobile views.
1. Start on the page http://localhost:3000/emotion-selection-web
2. Choose your emotion
3. You will be redirected to the http://localhost:3000/emotion-type and …

VIB-9: Refactor Meme Selection for mobile-friendly layout

---

app/javascript/components/Header.js
app/javascript/components/UI/Menu.js

[![VIB-83](https://badgen.net/badge/JIRA/VIB-83/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-83) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
1) Changed background color for header to bg-white

VIB-83: The Header background color does not meet the specifications on all application pages for the logged-in user

---

app/assets/stylesheets/main.scss
app/assets/stylesheets/results.scss
app/javascript/components/UI/ShoutoutButton.js
app/views/home/sent.html.erb

[![VIB-77](https://badgen.net/badge/JIRA/VIB-77/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-77) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Update the CSS to position the Shoutout button in the bottom right corner of the footer

VIB-77: Update Footer Layout

---

app/javascript/components/Pages/IcebreakerQuestion.js
app/javascript/components/requests/axios_requests.js

[![VIB-56](https://badgen.net/badge/JIRA/VIB-56/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-56) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
**Description**
This pull request improves error handling for API requests in the IcebreakerQuestion component by implementing user-friendly error alerts using SweetAlert2 (Swal) and enhancing the apiRequest function to accept a custom error handler.
Key Updates:
1. Added Error Handling in IcebreakerQuestion.js.
- Introduced Swal.fire() alerts to notify users about API errors. 
- Specific handling for HTTP 422 …

VIB-56  Submit button does not work on icebreaker-question page when entering question that already exists in database

---

app/assets/images/complete50.svg
app/assets/images/complete50_act.svg
app/assets/stylesheets/application.bootstrap.scss
app/assets/stylesheets/dropdown_select.scss
app/javascript/components/Pages/ProductivityBadFollowUp.js
app/javascript/components/Pages/ProductivityCheckLow.js
app/javascript/components/Pages/TimesheetPage.js
app/javascript/components/ResponseFlow.js
app/javascript/components/UI/DropdownSelect.js
app/javascript/components/UI/Menu.js
app/javascript/components/helpers/routes.js
package.json
yarn.lock

[![VIB-62](https://badgen.net/badge/JIRA/VIB-62/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-62) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
1. Add React Bootstrap Typeahead to dependencies.
2. Create DropdownSelect component.
3. Create dropdown_select.scss for customized styles according to the markup.
How to test:
https://www.loom.com/share/a0b7455b6d9845a4b418c0f52ea1866b?sid=8d8d23be-1f00-4655-aa04-ae74abbb179a

VIB-62: Create the DropdownSelect Component

---

app/assets/images/complete50.svg
app/assets/images/complete50_act.svg
app/javascript/components/Pages/TimesheetPage.js
app/javascript/components/ResponseFlow.js
app/javascript/components/UI/Menu.js
app/javascript/components/helpers/routes.js

[![VIB-48](https://badgen.net/badge/JIRA/VIB-48/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-48) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
VIB-48: Create the TimesheetPage Component
- Added TimesheetPage.js;
- Used Layout for the responsiveness;
- Added Back and Skip buttons to the bottom of the page;
1. Navigate to localhost:3000/timesheet, ensure correct rendering and responsiveness.
2. Back Button – Click Back, verify it returns to the previous page.
3. Skip button should be on the page, Submit button will be implemented later (no functionality yet).
4. …

VIB-48: Create the TimesheetPage Component

---

app/assets/stylesheets/main.scss
app/javascript/components/Footer.js
app/javascript/components/Pages/Recognition.js
app/javascript/components/UI/ShoutoutButton.js

[![VIB-84](https://badgen.net/badge/JIRA/VIB-84/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-84) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
1. Restored styles and animation settings for the ShoutoutButton component.
2. Updated styles to ensure correct animation on mobile versions.
3. Changed the initial point of the animation direction (from left-bottom to right-bottom).
4. The ShoutoutButton is not rendering in the footer on the Recognition page.
[Video how it works](https://www.loom.com/share/e58cec341ff7426fa06415ce5ccd72 …

VIB-84: The design of the recognition page does not meet the specifications for the logged-in user

---

app/javascript/components/UI/Menu.js

[![VIB-95](https://badgen.net/badge/JIRA/VIB-95/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-95) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Fixed the array of steps in Menu.js when the array cannot find the length property.

VIB-95: Blank page with browser error console appears after clicking "Unsubscribe from future check-ins" link in Emotion selection email notification

---

app/javascript/components/Pages/TimesheetPage.js
app/javascript/components/UI/BlockLowerBtns.js
app/javascript/components/UI/TimesheetRow.js
app/javascript/components/helpers/helpers.js

[![VIB-66](https://badgen.net/badge/JIRA/VIB-66/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-66) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Added a helper function that validates the correctness of each field
- Added message to the users if not all fields are filled up
- Update logic for the Submit button disabling
https://www.loom.com/share/539ce05fb7504ff6965dcb3fe204c668?sid=6d9f5c1b-6d3a-4a69-9809-15f6f5918c4d

VIB-66: Implement field validation (part of Create Timesheet page)

---

app/controllers/api/v1/emotions_controller.rb
app/javascript/components/App.js
app/javascript/components/Pages/ProductivityBadFollowUp.js
app/javascript/components/Pages/ProductivityCheckLow.js
app/javascript/components/Pages/TimesheetPage.js
app/javascript/components/UI/TimesheetRow.js
app/javascript/components/helpers/helpers.js
spec/requests/emotions_spec.rb

[![VIB-61](https://badgen.net/badge/JIRA/VIB-61/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-61) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Used existing apiRequest() function to fetch data
- Add warning messages if there are errors during fetching or project codes are empty
- Implement timesheet_enable functionality and render Timesheet page only for users who is in the Enabled Team
- Format code with Prettier for TimeSheetPage

VIB-61: Fetch Timesheet Data from API

---

app/admin/teams.rb
app/services/importers/team_csv_importer.rb
app/views/admin/teams/import.html.erb
spec/admin/teams_spec.rb

[![VIB-97](https://badgen.net/badge/JIRA/VIB-97/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-97) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- The controller action was split into separate actions for POST and GET HTTP methods
- Moved the internal logic of the action to a service
- Added an alert text and checked if the CSV file is correct
- Improved the database queries

VIB-97: Error message "We're sorry..." with console error appears in Active Admin after clicking 'Import' without uploading file in Teams tab

---

app/assets/stylesheets/buttons.scss
app/assets/stylesheets/design_system_vibereport.scss
app/assets/stylesheets/gif.scss
app/assets/stylesheets/icebreaker_answer.scss
app/assets/stylesheets/main.scss
app/javascript/components/Pages/MemeSelection.js
app/javascript/components/Pages/Recognition.js
app/javascript/components/UI/ShareContent.js
app/javascript/components/UI/ToggleEmotionType.js
app/javascript/components/UI/rich-text/DropDownList.js
app/javascript/components/UI/rich-text/RichTextArea.js

[![VIB-103](https://badgen.net/badge/JIRA/VIB-103/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-103) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
1. Fixed the sizes for the search results container.
2. Fixed styles for headings and the BigBtnEmotion button.

VIB-103: The GIPHY search results container changes size when uploading a custom GIF or entering invalid data on the meme-selection page

---

app/assets/stylesheets/main.scss
app/assets/stylesheets/results.scss
app/javascript/components/Pages/ResultsPageManager/EmotionIndex.js
app/javascript/components/Pages/ResultsPageManager/NavigationBar.js
app/javascript/components/Pages/ResultsPageManager/index.js
app/javascript/components/UI/ShareContent.js

[![VIB-102](https://badgen.net/badge/JIRA/VIB-102/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-102) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Hello Team, please review PR
- Made the Navigation button responsive
- Made charts responsive
>Note: To be able to properly style charts that are built with `recharts`, I have to add some custom media queries to the code, unfortunately, Bootstrap classes did not work very well
Desktop
Mobile

VIB-102: The design of the result-managers page does not meet the specifications for mobile, tablet, and web views

---

app/mailers/user_email_mailer.rb
app/views/user_email_mailer/auto_remind_checkin.html.erb

[![VIB-112](https://badgen.net/badge/JIRA/VIB-112/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-112) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
1) Modified `@who_is_waiting` message to remind users to fill out their timesheets.
2)  Added `user_belongs_to_timesheet_team?` method to check team settings.

VIB-112: Modify auto_remind_checkin mailer for users who need to enter timesheets

---

app/javascript/components/helpers/helpers.js

[![VIB-111](https://badgen.net/badge/JIRA/VIB-111/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Hello Team, please review PR
- Remove from word counts punctuations
- Only words with three letters or more will be counted (hi, by, it, is will not be counted)
- At least three words with three letters or more are required for the button to become enabled

VIB-111: Force shoutouts to say something about the people

---

app/assets/stylesheets/timesheetpage.scss

[![VIB-108](https://badgen.net/badge/JIRA/VIB-108/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-108) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
1. The vertical scrollbar is hidden.
2. The horizontal scrollbar has been given a default height, and the white background color has been removed
3. The scrollbar changes have been coordinated with the QA team.

VIB-108: The Design of the drop-down menu does not match specs on Timesheet page

---

app/javascript/components/Pages/RatherNotSay/RatherNotSay.js
app/javascript/components/Pages/RatherNotSay/SkipAhead.js
app/javascript/components/Pages/UnsubscribePage.js
app/javascript/components/helpers/helpers.js

[![VIB-125](https://badgen.net/badge/JIRA/VIB-125/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-125) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Updated font size on buttons
- Refactored components: UnsubscribePage, RatherNotSay, and SkipAhead

VIB-125: The font size of the buttons does not match the specifications on the unsubscribe, rather-not-say and skip-ahead pages in the web view

---

app/javascript/components/Pages/IcebreakerAnswer.js
app/javascript/components/Pages/IcebreakerQuestion.js
app/javascript/components/Pages/ResultsPage/QuestionSection.js

[![VIB-123](https://badgen.net/badge/JIRA/VIB-123/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-123) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
Hello Team, please review PR
- Fixed "@" symbol rendering
- Add margins to the question

VIB-123: The "@" symbol is missed in the text "Brought to us by "@" {user name}" on the icebreaker-answer page

---

app/admin/projects.rb
app/admin/time_periods.rb
app/admin/time_sheet_entries.rb
app/admin/time_sheet_entry.rb
app/assets/stylesheets/active_admin.scss
app/controllers/api/v1/projects_controller.rb
app/javascript/components/Pages/TimesheetPage.js
app/mailers/application_mailer.rb
app/mailers/time_sheet_mailer.rb
app/mailers/user_email_mailer.rb
app/models/project.rb
app/models/time_sheet_entry.rb
app/serializers/project_serializer.rb
app/services/exporters/time_sheet_csv_exporter.rb
app/services/importers/team_csv_importer.rb
app/views/time_sheet_mailer/time_sheet_results_email.html.erb
app/workers/time_sheet_results_email_worker.rb
db/migrate/20250410075348_add_usage_to_projects.rb
db/migrate/20250410084412_set_existing_projects_to_billable.rb
db/schema.rb
spec/factories/projects.rb
spec/mailers/previews/time_sheet_mailer_preview.rb
spec/mailers/time_sheet_mailer_spec.rb
spec/models/project_spec.rb
spec/models/time_sheet_entry_spec.rb
spec/requests/projects_spec.rb

[![VIB-126](https://badgen.net/badge/JIRA/VIB-126/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-126) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Added Usage field to project model
- Updated sync logic, to include Usage
- Disable submitting billable entries for 40+ hours
- Updated Time Periods in ActiveAdmin to include Participation by Team
- Added functionality to download timesheet entries CSV from ActiveAdmin
- Include CSV in mail

VIB-126: Timesheets Enhancements

---

app/mailers/emoji_reactions_mailer.rb
app/views/emoji_reactions_mailer/emoji_reaction_email.html.erb
app/workers/emoji_reaction_email_worker.rb
lib/tasks/emoji_reaction_notification.rake
spec/mailers/emoji_reactions_mailer_spec.rb

[![VIB-149](https://badgen.net/badge/JIRA/VIB-149/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-149) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Added mailer to send email for shoutouts that get reactions
- Styled view for this email (I used inline styles and table, so it will be easier recognize by different mail clients)
- Create a worker and rake task
- Added specs for mailer
Mobile
Desktop

VIB-149: Send out daily emails for shoutouts that get reactions

---

app/controllers/api/v1/emotions_controller.rb
app/javascript/components/Pages/IcebreakerAnswer.js
app/javascript/components/Pages/IcebreakerQuestion.js
app/javascript/components/Pages/ResultsPage/QuestionSection.js
app/javascript/components/Pages/ResultsPage/ShoutoutAwards.js
app/javascript/components/helpers/helpers.js

[![VIB-140](https://badgen.net/badge/JIRA/VIB-140/009900)](https://cloverpop-internship-2025.atlassian.net/browse/VIB-140) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=wahanegi&utm_campaign=badge_info)
- Made use of the existing helper function to update first_name with the full name

VIB-140: Adjust how names are shown on the Results page
